### ISSUE TITLE
Login bug

### ISSUE THREAD

**Issue by ifmelchor** [fangkehou-team/BingGPT#1]
There is a login bug. 

Once you log in and try to move to chat, the app asks to log in again, like a loop.

**Comment by che77a38** [comment]
![image](https://github.com/fangkehou-team/BingGPT/assets/27732581/cccbf797-e385-4d85-b3a6-5bf0cef5160d)
I can't log in.Click login invalid

**Comment by lony2003** [comment]
Well actually it works, just a few days ago, but it just won't work these days🥲🥲🥲. I will fix that and release a new version of it. so hold on, the new version is on the way!😊😊😊 Anyway, thank you again for contributation!

**Comment by lony2003** [comment]
the new version of bingGPT has been released. Please update to the latest version.
