### ISSUE TITLE
[BUG] mac 下应用无法用鼠标移动

### ISSUE THREAD

**Issue by ericxie008** [fangkehou-team/BingGPT#10]
![1705042205079](https://github.com/fangkehou-team/BingGPT/assets/8163851/df88f92a-b479-4636-ad61-323d9b123068)
应用顶部全部被切换条挡住, mac下无法用鼠标拖动

**Comment by lony2003** [comment]
额。。。。。。是我模板写的不清楚吗，为什么不按照模板提供的格式创建issue呢？或者你看不到issue模板吗
