### ISSUE TITLE
[BUG] 应用顶部栏不能用鼠标进行拖动

### ISSUE THREAD

**Issue by ericxie008** [fangkehou-team/BingGPT#11]
**Version Check**
- [x]  I have checked and the version I'm running is up to date.

**State Check**
- [x] I have tried right click and menu have shown.
- [x]  I can see the splash or loading screen.

**Duplication Check**
-  [x]  I have searched the issue list and haven‘t found any imformation about my issue.

**Describe the bug**
应用顶部栏不能用鼠标进行拖动

**To Reproduce**

**Expected behavior**
鼠标可以进行拖动

**Screenshots**
If applicable, add screenshots to help 
![1705042205079](https://github.com/fangkehou-team/BingGPT/assets/8163851/47774076-3d22-4748-aef4-fc701e0d64c4)
如图所示,没有可以进行鼠标拖动的地方

**Desktop (please complete the following information):**
 - OS: macos 13.6.3 (22G436) 
 - Program Version 版本0.4.3 (0.4.3)
 - 
<img width="293" alt="截屏2024-01-12 15 11 12" src="https://github.com/fangkehou-team/BingGPT/assets/8163851/f48a507b-38d9-4095-bb85-e9d1192f28a5">

**Additional context**

**Comment by ericxie008** [comment]
补充下intel 芯片的mac os

**Comment by lony2003** [comment]
刚才发了个新版本，你可以试一下。这个问题windows上也有，因为我日常是linux所以前几个版本编译的时候没有意识到这个问题，今天在windows上修复的，在win下肯定是没问题了，你可以看一下macos上这个问题有没有修复，毕竟我没有mac。

顺便帮我看看macos上的图标是不是方块形的图标哈。

**Comment by ericxie008** [comment]
已经修复了, 图标也是方块的
