### ISSUE TITLE
windows-0.4.4 The page is blank after login

### ISSUE THREAD

**Issue by 17006751** [fangkehou-team/BingGPT#12]
windows-0.4.4 The page is blank after login
<img width="442" alt="Snipaste_2024-01-14_16-18-28" src="https://github.com/fangkehou-team/BingGPT/assets/117696031/a452a4c5-de39-4320-8d6e-0f59f39ec12f">

**Comment by lony2003** [comment]
Please follow the template and fill in the necessary information.
