### ISSUE TITLE
[BUG] Getting cookies takes forever

### ISSUE THREAD

**Issue by GoldThunder** [fangkehou-team/BingGPT#13]
**Version Check**
- [X] I have checked and the version I'm running is up to date.

**State Check**
- [X] I have tried right click and menu have shown.
- [X] I can see the splash or loading screen.

**Duplication Check**
- [X] I have searched the issue list and haven‘t found any imformation about my issue.

**Describe the bug**

Hello, just open the app and it stays at getting cookies, wait for 20 seconds nothing, wait for 10 minutes nothing

the program auto updated from 0.4.4

id like to be able to disable updates , mainly because I use tether internet from my phone and any update is over 100mb kills me, the reason why I download this is because browser open takes abt 8mb just from pictures and stuff , it'd be nice to have notification then ask to update instead of just downloading all my fathers internets data Q,Q

**To Reproduce**

just open the app and it never finishes getting the cookies
 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows
 - Arch: 64 bit
 -  [ 0.4.5] --updated from 0.4.4

**Comment by lony2003** [comment]
Thanks for advice. Actually I don't have any experence about electron-builder, I'll change that behavior on next version.

And to solve the problem, could you open the app, and head to the get cookies page, and then click ctrl + shift + i (for windows, shift + cmd + i if you're using macos), and then in devtools head to console page and take a screenshoot about the error log? Thanks.

**Comment by GoldThunder** [comment]
I cant get it to show, i think im doing something wrong, when you mean the get cookies page do you mean this page ?

![image](https://github.com/fangkehou-team/BingGPT/assets/44780578/2cada7cb-5c7a-4167-8a70-3983cdaf9339)


if so nothing happens when i pressed shift+cntrl+i 

i have opened the programm as admin , 

the only configuration i used is never shown ask for passwords and never show login screen again maybe that is? let me check

**Comment by GoldThunder** [comment]
i also deleted app data, reinstalled from 0.4.5, always ask for signin and never stay signed in and still doesnt work, is there any other folder i can delete to test? 

i only know a bit of csharp and for unity i wish i knew js , how do u change stuff from the webpage? is it do you wait til the files get downloaded then modify the js code in it? aww this is such a convenient way to use gpt uwu such a chame microsft changes stuff all the time

**Comment by lony2003** [comment]
> is it do you wait til the files get downloaded then modify the js code in it?

Well, actually you can check #6 for that. It's a feature of Electron.

> is there any other folder i can delete to test?

nope. I have no idea about that. The only way to check the error is to open the Electron devtools. Currently, the only way open it is the shortcut ([ ctrl + shift + i ] or [ ctrl + alt + i ]). Maybe I can add a new button in the menu, but the current version doesn't have it. You can try [ ctrl + alt + i ] to open the devtools.

**Comment by lony2003** [comment]
Well, it turns out that it's just a stupid mistake I have made. I have released a new version to fix that problem and change the behavior of the update process. Could you help me figure out if the problem is solved?

**Comment by lony2003** [comment]
Well, it turns out that it's just a stupid mistake I have made. I have released a new version to fix that problem and change the behavior of the update process. Could you help me figure out if the problem is solved?

**Comment by GoldThunder** [comment]
IT WERKS!!!

![image](https://github.com/fangkehou-team/BingGPT/assets/44780578/af1b6de1-e960-4f68-8b3a-a804b818dcea)


hey the cookies screen is solved

anyway :) the cookies screen always comes up is it normal hehe great fix friend wuhuu

**Comment by GoldThunder** [comment]
updating works i was auto updated aswell ^^

how ever i dont think i was prompted to update and also still cant open developer options u.u

**Comment by lony2003** [comment]
>  the cookies screen always comes up is it normal

Yes, it's normal. I don't know the process that how bing refresh their cookies, but they definitely will. So instead of letting users refresh themselves then it's expired, I think it's a good way to refresh it everytime the app open.

> updating works i was auto updated aswell

From `v0.4.6`, the app has changed the behavior of the update process. Users can now decide for themselves whether and when to update.

> cant open developer options

The right click menu now has the `Open Devtools` button.

Further informations, issues and PRs are welcomed. Thanks for contribution!
