### ISSUE TITLE
[Feature] 如果有可能，请解决下使用限制问题。

### ISSUE THREAD

**Issue by kxsw419** [fangkehou-team/BingGPT#15]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 

### Description

我记得以前使用binggpt的时候没有使用限制，但现在好像是限制了提问数量，不知道大佬能否解决下。
![iShot_2024-02-18_19 41 40](https://github.com/fangkehou-team/BingGPT_Enhanced_Editon/assets/112813915/b00d00ac-a859-47a8-8483-82df5d3a90f0)
![iShot_2024-02-18_19 40 55](https://github.com/fangkehou-team/BingGPT_Enhanced_Editon/assets/112813915/8eaf0f58-7726-4cf9-9aec-9a94aca5bf51)
![iShot_2024-02-18_17 52 49](https://github.com/fangkehou-team/BingGPT_Enhanced_Editon/assets/112813915/e06fd2ff-0504-4dd5-bcd5-2a2841da77ed)

**Comment by foxypiratecove37350** [comment]
Bro, all the world isn't chinese so use english please, I know that there is Google Translate but it make really poor translation so please help we to help you by using english.

**Comment by lony2003** [comment]
这个没办法，这个是bing那边的限制了。作为一个壳子，其实这个app能做到的并不多，更多的限制其实是在微软那边。

但还请注意，你的issue标题并不符合社区规范，请查看其他issue的标题并做出适当的修改。

请在标题前加入 `[Feature] ` 。方便其他贡献者作参考。感谢你对社区做出的贡献！

**Comment by lony2003** [comment]
> Bro, all the world isn't chinese so use english please, I know that there is Google Translate but it make really poor translation so please help we to help you by using english.

@foxypiratecove37350 Bro, if you check out the issue template of our community, you will find out that our community supports both english and chinese. Just like you can't speak Chinese, not all Chinese people can speak English fluently, but this does not mean that you can't ask questions if you don't speak English. I believe that language and race cannot be shackles that hinder contribution. Some of the sentences I just wrote were generated using this application, and I think that usage is a good example for someone who don't know the language and the culture of another country to communicate with people in that country. This usage is also the greatest convenience that I think LLMs bring to communication between people. After all, thanks for your contribution and wish you have a nice day!

**Comment by kxsw419** [comment]
感谢回复，以后我注意标题格式
