### ISSUE TITLE
[BUG] 在mac 中无法粘贴文字

### ISSUE THREAD

**Issue by ericxie008** [fangkehou-team/BingGPT#16]
### Verify steps

- [X]  The version I'm running is up to date. 已安装最新版本. 
- [X]  I have tried right click and menu have shown 单击鼠标右键正常显示菜单 
- [X]  I can see the splash or loading screen. 可以正常看到屏幕中有显示加载或首页的内容 
- [X]  I have searched on the [issue tracker](……/) for a related issue. 我已经在 [Issue Tracker](……/) 中找过我要提出的问题 

### BingGPT Version
软件版本

v0.4.3

### What OS are you seeing the problem on?
操作系统/桌面环境

macOS

### What Architecture are you seeing the problem on?
系统指令集

x86

### Description

在mac 中使用command+c复制一段文字, 再使用command+v 粘贴文字, 无法粘贴, 需要使用鼠标右键调出paste 方法才能粘贴

### Error Logs

无

### Steps To Reproduce

同描述

**Comment by lony2003** [comment]
说实话我并不清楚macos的快捷键的机制，请安装最新版本 v0.4.7 再试试

如果不行的话我再看看

**Comment by ericxie008** [comment]
下载BingGPT-Mac-x64-0.4.7-Installer.dmg 的安装包安装后右键显示app 信息还是显示为v0.4.3,还是存在这个问题
<img width="415" alt="截屏2024-03-01 15 27 51" src="https://github.com/fangkehou-team/BingGPT_Enhanced_Editon/assets/8163851/3d644444-1c8c-4ad3-8cfa-58134e0b311b">
使用键盘的粘贴命令依旧不能粘贴文字

**Comment by lony2003** [comment]
emmmmm......我大概是知道怎么回事了，在macos的标准键盘中并没有ctrl这个键，但目前electron默认的快捷键都是ctrl打头的，这就造成了command+v无法触发。我看看吧，这个问题估计是一段时间内都不会修复了，在我处理完新版本之前不会考虑对其进行修复，或者你也可以使用robotjs自行修复，详见这里：https://stackoverflow.com/questions/60712110/how-to-execute-os-paste-action-via-electron

**Comment by ericxie008** [comment]
好吧, 我自己下载源码, 捣鼓了下electron , 已经修正了, 但不是你上面的方法

**Comment by ericxie008** [comment]
使用的是 https://juejin.cn/post/7154964098231304199
教程中的第一个

**Comment by lony2003** [comment]
OK，知道了。
如果可以的话，你可以给这个项目提交一个PR，这样我就省的修了[doge]

**Comment by lony2003** [comment]
在PR信息中添加 `close #16` 字样即可自动关闭该issue。

**Comment by lony2003** [comment]
fixed in v0.4.8, issue closed.
