### ISSUE TITLE
[BUG] 启动后无法进入 Cpilot 界面, 只有 BING 首页

### ISSUE THREAD

**Issue by xjArea** [fangkehou-team/BingGPT#17]
### Verify steps

- [X]  The version I'm running is up to date. 已安装最新版本. 
- [X]  I have tried right click and menu have shown 单击鼠标右键正常显示菜单 
- [X]  I can see the splash or loading screen. 可以正常看到屏幕中有显示加载或首页的内容 
- [X]  I have searched on the [issue tracker](……/) for a related issue. 我已经在 [Issue Tracker](……/) 中找过我要提出的问题 

### BingGPT Version
软件版本

0.4.7

### What OS are you seeing the problem on?
操作系统/桌面环境

Windows

### What Architecture are you seeing the problem on?
系统指令集

x86

### Description

之前是可以正常运行的, 但今天有问题了, 最初是交谈不顺畅, 显示我们正在处理错误什么的, 但文章扩展的功能还能用, 然后再启动就只有必应首页, 不再显示 Cpilot 的界面了. 

### Error Logs

none

### Steps To Reproduce

none

**Comment by lony2003** [comment]
请检查你的Bing首页是国际版还是国内版，有可能是魔法没有生效，导致bing引流到了国内站

**Comment by xjArea** [comment]
噢, 是魔法出了错误, 已经解决, 打扰了😅
