### ISSUE TITLE
[BUG] 登入后只剩下顶部两个按钮, 无其他内容, 无法进行操作

### ISSUE THREAD

**Issue by xjArea** [fangkehou-team/BingGPT#18]
### Verify steps

- [X]  The version I'm running is up to date. 已安装最新版本. 
- [X]  I have tried right click and menu have shown 单击鼠标右键正常显示菜单 
- [X]  I can see the splash or loading screen. 可以正常看到屏幕中有显示加载或首页的内容 
- [X]  I have searched on the [issue tracker](……/) for a related issue. 我已经在 [Issue Tracker](……/) 中找过我要提出的问题 

### BingGPT Version
软件版本

0.4.7

### What OS are you seeing the problem on?
操作系统/桌面环境

Windows

### What Architecture are you seeing the problem on?
系统指令集

x86

### Description

之前是可以正常运行的, 但昨天开始出问题了, 启动后有显示登录和必应首页的内容, 但之后的 Copilot 界面就只会显示顶部的 Chat 和 Compose 按钮, 按钮可以点击, 但按钮下面一片空白, 没有任何内容. 

### Error Logs

DevTool 错误信息: 

`Refused to frame 'https://edgeservices.bing.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self' edge://*/ edge-hybrid:".`

`TypeError: Cannot read properties of undefined (reading 'shadowRoot')
    at EventEmitter.<anonymous> (X:\…\BingGPT\resources\app.asar\dist-electron\preload.js:278:1379)
    at EventEmitter.emit (node:events:513:28)
    at Object.onMessage (node:electron/js2c/renderer_init:2:9240)`

### Steps To Reproduce

none

**Comment by xjArea** [comment]
右键空白位置点击 `Reset`, 然后重新登录就可以了😂

**Comment by xjArea** [comment]
噢, 这个问题又出现了, 这次 Reset 并重新登录也无效了, DevTool 的错误信息依然为: `Refused to frame 'https://edgeservices.bing.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self' edge://*/ edge-hybrid:".`

**Comment by lony2003** [comment]
我提交了一个版本，你可以试试Github Actions里的每日构建是不是能用了，我现在本地的分支是在搞多用户所以暂时没法测。

另外想问你个问题，你觉得多用户是这个项目需要的东西吗？因为我自己是没这个需求的但是我又觉得这玩意有点重要，我感觉我做了这么长时间结果我自己没有需求别人也没有需求有点得不偿失。

asar会替换吧，不会替换自己去Google一下，下对应你系统的构建就OK。

**Comment by xjArea** [comment]
我不懂构建, 但可以试试, 谢谢你~💖

另外, 多用户的问题是在问我吗? 好吧, 我认为这是个搞笑的伪需求, 我甚至无法设想在什么情况下需要多用户的功能, 这个软件的潜在用户群体会跟人共用机器吗? 如果你是拿软件来练手学习, 那无所谓得不偿失, 但如果是真的想弄这个功能服务用户, 那这玩意真的没啥子意义, 使用率能达到 `1%` 都是高估了, 还是说我对"多用户"的理解有误, 你能举例说明什么场景需要它吗…

**Comment by lony2003** [comment]
> 好吧, 我认为这是个搞笑的伪需求

有道理。我没有拿这玩意练手的想法，太简单没必要。这个东西目前对我来说已经挺完美的了，既然是伪需求，那我就没有必要画蛇添足了。

> 你能举例说明什么场景需要它吗…

最开始的时候Bing Chat有每日限额，如果有大量的需求的话可能就会有多个账号，不过现在好像是没有了，所以这个需求应该不是个需求了。感谢！我只是下不了决心停止做无用的事情罢了。


> 我不懂构建, 但可以试试, 谢谢你~💖

你可以在Actions页面找到最新的构建，我暂时不会发版，因为毕竟还没人测试过能不能用，你可以帮我测试一下能不能用

还有，你发的消息好像AI啊（虽然从有些词来看大概率不会是AI写出来的，不过从行文看真的好像[doge]）

**Comment by xjArea** [comment]
我在 <https://github.com/fangkehou-team/BingGPT_Enhanced_Editon/actions/runs/9509184405> 中下载了 `windows-latest.zip` 文件, 并将该压缩包里的 `app.asar` 解压后替换了 `BingGPT\resources\app.asar` 文件, 重启软件后, 发现无法弹出应用界面, 只是任务管理中出现了三个 BingGPT 的线程, 是我的操作哪里不对吗?

> 还有，你发的消息好像AI啊（虽然从有些词来看大概率不会是AI写出来的，不过从行文看真的好像[doge]）

这肯定是您的错觉, 人家才不是什么天网呢, 请无需怀疑, 人类万岁~ 😅

**Comment by lony2003** [comment]
操作应该是没问题的，我的问题，重新提交了一个，现在再看看吧，我这里是能用的，你再试试，还是最新的构建

你测完要是没啥问题我就发版了。

**Comment by xjArea** [comment]
这回可以弹出应用窗口了, 但是窗口里没有任何内容, DevTool 内也没有任何信息…

**Comment by lony2003** [comment]
嘶。。。。不能啊，你开梯子了吗？

或者你可以试一下在命令行里打开这个应用吗？

命令行里可能会有错误信息

**Comment by xjArea** [comment]
```bash
libpng warning: iCCP: cHRM chunk does not match sRGB
Checking for update
[8772:0614/115132.231:ERROR:cache_util_win.cc(20)] Unable to move the cache: 拒绝访问。 (0x5)
[8772:0614/115132.237:ERROR:cache_util_win.cc(20)] Unable to move the cache: 拒绝访问。 (0x5)
[8772:0614/115132.256:ERROR:disk_cache.cc(205)] Unable to create cache
[8772:0614/115132.256:ERROR:gpu_disk_cache.cc(676)] Gpu Cache Creation failed: -2
[8772:0614/115132.305:ERROR:disk_cache.cc(205)] Unable to create cache
[8772:0614/115132.305:ERROR:gpu_disk_cache.cc(676)] Gpu Cache Creation failed: -2
Error: net::ERR_FILE_NOT_FOUND
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:50234)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
(node:8772) electron: Failed to load URL: edge://…
/BingGPT/resources/app.asar/dist/index.html with error: ERR_UNEXPECTED
(Use `BingGPT --trace-warnings ...` to show where the warning was created)
Update for version 0.4.7 is not available (latest version: 0.4.7, downgrade is disallowed).
checkForUpdatesAndNotify called, downloadPromise is null
```

**Comment by lony2003** [comment]
emmmmmm.......好像windows的文件的表示方式和linux的不太一样，不过很可惜我用的linux，所以只能摸黑改了。我又提交了一个版本，稍稍修改了文件获取的逻辑，你可以再试试

**Comment by xjArea** [comment]
这回可以了, 能正常使用, 以下是命令行启动后的信息, 似乎还是有报错, 但不影响使用~ 😆
```bash
libpng warning: iCCP: cHRM chunk does not match sRGB
Checking for update
Update for version 0.4.7 is not available (latest version: 0.4.7, downgrade is disallowed).
checkForUpdatesAndNotify called, downloadPromise is null
[9712:0614/122118.428:ERROR:ssl_client_socket_impl.cc(968)] handshake failed; 
    returned -1, SSL error code 1, net_error -107
[9712:0614/122118.429:ERROR:ssl_client_socket_impl.cc(968)] handshake failed; 
    returned -1, SSL error code 1, net_error -107
[10064:0614/122340.296:ERROR:CONSOLE(1)] "Request Storage.getStorageKeyForFrame failed. 
    {"code":-32602,"message":"Frame tree node for given frame not found"}", 
    source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
```

**Comment by lony2003** [comment]
能用就成了，这个大概率错误不是我的原因，我稍后发个版。
