### ISSUE TITLE
Permanent black screen

### ISSUE THREAD

**Issue by ifmelchor** [fangkehou-team/BingGPT#2]
In version 0.4.1, 
when I try to open application, a permanent black screen is shown.
I am using linux mint (ubuntu bionic)

**Comment by lony2003** [comment]
bro, I can't know the error you meet if you don't discribe your problem more specifically. In the program, click `ctrl+shift+i` and it will open a devtools window. on the console tab you can find the error log. Please provide me the log so I can have a look.

**Comment by ifmelchor** [comment]
I have no response after press `ctrl+shift+i`

This is what I have after running the app:

![Screenshot from 2023-12-19 09-17-26](https://github.com/fangkehou-team/BingGPT/assets/44578518/09130c1c-7910-4354-bac8-44efa7adfe52)

**Comment by lony2003** [comment]
hmmmmm it seems that electron itself is crashed. I will try to fix that.

**Comment by lony2003** [comment]
v0.4.2 has released and the blank error is solved. Please update to the latest version.

**Comment by Shazgul** [comment]
Exact same Error here.

**Comment by lony2003** [comment]
> Exact same Error here.

@Shazgul Have you upgraded to the latest version? If so, you can open a new issue to describe your problem
