### ISSUE TITLE
[BUG] [WIP] Font size not changing on Mac (idk other oses.)

### ISSUE THREAD

**Issue by perlytiara** [fangkehou-team/BingGPT#23]
### Verify steps

- [X]  The version I'm running is up to date. 已安装最新版本. 
- [X]  I have tried right click and menu have shown 单击鼠标右键正常显示菜单 
- [X]  I can see the splash or loading screen. 可以正常看到屏幕中有显示加载或首页的内容 
- [X]  I have searched on the [issue tracker](……/) for a related issue. 我已经在 [Issue Tracker](……/) 中找过我要提出的问题 

### BingGPT Version
软件版本

Latest dev built.

### What OS are you seeing the problem on?
操作系统/桌面环境

macOS

### What Architecture are you seeing the problem on?
系统指令集

x86

### Description

When i right click select to change the front it well even with a reload it doesn't update it to be bigger as i can see.
Does it work for you ?

### Error Logs

N/A

### Steps To Reproduce

N/A

**Comment by lony2003** [comment]
Please refer to the release note for that problem. In fact, I havent found a proper way to solve that. May be I would delete that options in the future.

**Comment by perlytiara** [comment]
I apoligize i didn't get that release note issue figured before hand but yes it would help my melting eyes strangely haha take your time, but yes much love and appreciation upon that furthering this app this great have a great fantastic day you really did put all of your mind to my latest demand i coulnd't ask for more and i also tried to add during the whole night god bless you man so that's that. take care let's we can keep in touch ! for now.
