### ISSUE TITLE
warning error during dpkg install (linux)

### ISSUE THREAD

**Issue by ifmelchor** [fangkehou-team/BingGPT#3]
I downloaded 0.4.2 version, then
before installing .deb via dpkg, I get:

```
Preparing to unpack BingGPT-Linux-amd64-0.4.2.deb ...
Unpacking binggpt (0.4.2) over (0.4.1) ...
Setting up binggpt (0.4.2) ...
update-alternatives is /usr/bin/update-alternatives
update-alternatives: using /opt/BingGPT/binggpt to provide /usr/bin/binggpt (binggpt) in auto mode
Error in file "/usr/share/applications/xreader.desktop": "application/x-ext-cbzapplication/oxps" is an invalid MIME type ("application/x-ext-cbzapplication/oxps" contains an invalid character in the subtype)
Processing triggers for desktop-file-utils (0.26+mint3+victoria) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu3) ...
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
```

Despite the error: 

**Error in file "/usr/share/applications/xreader.desktop": "application/x-ext-cbzapplication/oxps" is an invalid MIME type ("application/x-ext-cbzapplication/oxps" contains an invalid character in the subtype)**

I could interact with the bing chat

I am using Linux Mint (ubuntu bionic)

**Comment by lony2003** [comment]
This is your own problem, please check yourself. our build doesn't have this file.

**Comment by cesarbrancalhao** [comment]
This is a problem with Mint. It's a typo in xreader.

To fix this. open your terminal and
```fortran
$ cd ../../usr/share/applications/
$ sudo nano xreader.desktop
```

Now scroll all the way down to `MymeType=`, find `application/x-ext-cbzapplication/oxps` and put semicolons between x-ext-cbz and application, like this: `application/x-ext-cbz;application/oxps`

Save and exit then type `sudo apt update` and retry the dpkg.
