### ISSUE TITLE
No arm64 version to use on Raspberry Pi ?

### ISSUE THREAD

**Issue by PictorSomni** [fangkehou-team/BingGPT#5]
Hi,

I'm sure i cannot be the only one who wishes to use this app on a Raspberry Pi.
Is it possible to have a Linux arm64 version ?

I use only Python / CircuitPython, i don't know much about web frameworks. 

Have a nice day,
Charles

**Comment by lony2003** [comment]
hmmmmmmm.........Well, thounds esay, I think I can try to build the arm64 version on next release.

**Comment by PictorSomni** [comment]
Thanks !

**Comment by lony2003** [comment]
New version with arm64 build was released! Further report are welcome. Please head to Discussion for further questions except bugs.
